#!/bin/bash


echo " "
echo " "
echo " "
echo "This is the CLI terminal for controlling the wifi robot car, here are the available commands:"
echo "-----------------------------------------------------------------------"
echo " "
echo "The values corresponding to the symbols are shown below: "
echo "X = 0.00 is the minimum value, and 1.00 will run it in a direction for aproximately 1 meter."
echo "Y = 0.00 is the minimum value, and 1.00 will rotate it in a direction for aproximately 90 degrees."
echo "Z = The name of the image, or bulk of images to save, should be unique each time."
echo "For live camera feed, you can visit http://192.168.1.66/html/ , ofcourse you must be on the same local network, due to safety reasons."
echo " "
echo "robot_move_forward X"
echo "robot_move_backward X"
echo " "
echo "robot_look forward"
echo "robot_look backward"
echo "robot_look left"
echo "robot_look right"
echo " "
echo "robot_rotate_left Y"
echo "robot_rotate_right Y"
echo " "
echo "robot_snapshot Z"
echo "robot_detection Z"
echo " "
echo " "
echo "Detailed explanation: "
echo "-----------------------------------------------------------------------"
echo " "
echo "The functions for moving forward, backward and rotating get the time delay as an argument, "
echo "which gets multiplied, so that the value 1 is aproximately 1 meter for moving and 90 degrees for rotating. "
echo " "
echo "The function for looking accepts a string as an argument (forward, backward left or right), which then rotates the usb camera in the preset position."
echo " "
echo "The snapshot function just takes a snapshot trough the usb camera, and uploads it to dropbox via the API"
echo " "
echo "The detection function starts a openCV human tracker loop, where the function constantly check images for humans,"
echo "and if humans are found, it draws a green rectangle around them, when 20 images are saved, it breaks the loop and the program finishes. "
echo "NOTE: The above detects alot of false positives."
echo " "
echo "------------------------------------------------------------------------"
echo " "
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!BEFORE STARTING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "It is very important, that before starting for the first time, you copy and paste these commands into the terminal"
echo " "
echo "alias robot_move_forward='python forward.py'"
echo "alias robot_move_backward='python backward.py'"
echo "alias robot_look='python look.py'"
echo "alias robot_rotate_left='python rot_l.py'"
echo "alias robot_rotate_right='python rot_r.py'"
echo "alias robot_snapshot='python snapshot.py'"
echo "alias robot_detection='python toggle_pedestrian_tracker.py'"
echo " "
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
