#!/bin/bash


echo " "
echo " "
echo " "
echo "Welcome to the LPP bus info terminal, here are your available commands:"
echo "-----------------------------------------------------------------------"
echo " "
echo "-To get information about live bus arrivals to a station, type: bus arrivals to 'station name'"
echo " "
echo "-To get the schedule of all bus routes, driving at a certain station, type: bus schedule at 'station name'"
echo "-To get the schedule of a bus driving a certain route, at a certain station, type: bus route 'route number' schedule at 'station name"
echo "    The two commands above this line can also be ended with: time 19:40, to show that you only want to know the first bus ride schedules that are after 19:40"
echo "    You can also end them with: now, instead of using time, to specify that you want the first schedule after the current time"
echo " "
echo "-To get the nearest stations to your geolocated ip point, type: bus nearest stations"
echo "-To get the nearest stations to your geolocated ip point, driving a certain route number, type: route 'route number' nearest stations"
echo "    The default radius for the two commands above is 1000 meters around your geolocated ip point, but you can modify this, by ending the above commands in radius 'number of meters radius'"
echo " "
echo "For usage see the examples below: "
echo "-----------------------------------------------------------------------"
echo "examples of usage :"
echo " "
echo "bus arrivals at pošta (returns time and bus info of incoming buses arriving into pošta station"
echo "bus schedule at pošta now (returns first schedule after current time, for all bus lines driving trough pošta station)"
echo "bus route 14 schedule at pošta time 19:40 (returns first schedule after 19:40 for buses driving route number 14 trough pošta station"
echo "bus route 14 nearest stations (returns all stations that have route 14 buses driving trough them, within a radius of 1000 meters of your geoip location"
echo "bus route 14 nearest stations radius 2000(returns all stations that have route 14 buses driving trough them, within a radius of 2000 meters of your geoip location"
echo "bus nearest stations (returns all stations within a radius of 1000 meters of your geoip location"
echo "bus nearest stations radius 2000 (returns all stations within a radius of 2000 meters of your geoip location"
echo " "
echo " "
echo " <!-- info --!>"
echo "Please note that i do not control what kind of data i get from the lpp servers (they have a few of the same entries sometimes)"
echo "For positions i use geoip service http://freegeoip.net/json which is sometimes unavailable, causing the nearest station functionality to not work."
echo "------------------------------------------------------------------------"
echo " "
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!BEFORE STARTING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "It is very important, that before starting for the first time, you type this command into terminal:"
echo " "
echo "alias bus='python lpp_bus.py'"
echo " "
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
